version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: cloudvault-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: >
        mongosh --port 27017 --quiet --eval " try { rs.status().ok } catch(e) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}).ok } "
      interval: 5s
      timeout: 10s
      start_period: 5s
      retries: 10

volumes:
  mongodb_data:
